name: Update node-packages.

on:
  schedule:
  - cron: "0 22 * * *"
  push:

jobs:
  auto-update:

    runs-on: ubuntu-latest
    env:
      git_user_name: github-actions
      git_user_mail: github-actions@github.com
    steps:
    - uses: actions/checkout@v4
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
        repository: calbrecht/f4s-nodejs
        ref: main
    - uses: cachix/install-nix-action@v22
    - run: nix run .github#auto-update
